// <auto-generated />
using System;
using CVAnalysis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVAnalysis.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CVAnalysis.Domain.Entities.AnalysisRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("analysis_type");

                    b.Property<Guid>("CVFileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cv_file_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("JobDescriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("job_description_id");

                    b.Property<DateTimeOffset?>("PartialResultExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("partial_result_expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("TimeoutAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("timeout_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("CVFileId");

                    b.HasIndex("JobDescriptionId");

                    b.HasIndex("Status", "TimeoutAt")
                        .HasDatabaseName("IX_AnalysisRequests_status_timeout");

                    b.HasIndex("UserId", "ContentHash", "Status")
                        .HasDatabaseName("IX_AnalysisRequests_dedup");

                    b.ToTable("AnalysisRequests", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("actor_role");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details_json");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("target_entity");

                    b.Property<string>("TargetEntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("target_entity_id");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ActorUserId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_actor_created");

                    b.ToTable("AuditLogs", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.CVFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExtractedData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extracted_data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("page_count");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_CVFiles_user_expires")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("CVFiles", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.CompensationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("CompensatedCreditType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("compensated_credit_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("CreditAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("credit_amount");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecisionNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("decision_notes");

                    b.Property<Guid>("ProposedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("proposed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("TechnicalRootCause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("technical_root_cause");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("ProposedByUserId");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CompensationRequests_ticket");

                    b.ToTable("CompensationRequests", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.CreditLedger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<Guid?>("AnalysisRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("analysis_request_id");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int")
                        .HasColumnName("balance_after");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("int")
                        .HasColumnName("balance_before");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CreditType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("credit_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("entry_type");

                    b.Property<Guid?>("PaymentOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_order_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_CreditLedger_user_created");

                    b.ToTable("CreditLedger", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.CreditPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CreditsAmount")
                        .HasColumnType("int")
                        .HasColumnName("credits_amount");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("package_name");

                    b.Property<decimal>("PriceVnd")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_vnd");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("CreditPackages", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.EmailHashRegistry", b =>
                {
                    b.Property<string>("EmailHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("email_hash");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset>("TrialBlockedUntil")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("trial_blocked_until");

                    b.HasKey("EmailHash");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("EmailHash"));

                    b.HasIndex("TrialBlockedUntil")
                        .HasDatabaseName("IX_EmailHashRegistry_blocked_until");

                    b.ToTable("EmailHashRegistry", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.JobDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("ExtractedSkillsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extracted_skills_json");

                    b.Property<bool>("MinRequirementsMet")
                        .HasColumnType("bit")
                        .HasColumnName("min_requirements_met");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("WordCount")
                        .HasColumnType("int")
                        .HasColumnName("word_count");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_JobDescriptions_user_created");

                    b.ToTable("JobDescriptions", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.OptimizedBulletPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CustomizedText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customized_text");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("original_text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("report_id");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("section_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("suggested_text");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ReportId")
                        .HasDatabaseName("IX_OptimizedBulletPoints_report");

                    b.ToTable("OptimizedBulletPoints", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("AmountVnd")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_vnd");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("CreditsAmount")
                        .HasColumnType("int")
                        .HasColumnName("credits_amount");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("gateway_transaction_id");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("order_code");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("package_id");

                    b.Property<DateTimeOffset?>("ReconciledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("reconciled_at");

                    b.Property<Guid?>("ReconciledByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reconciled_by_user_id");

                    b.Property<string>("ReconciliationNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("reconciliation_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_PaymentOrders_code");

                    b.HasIndex("PackageId");

                    b.HasIndex("ReconciledByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("IX_PaymentOrders_reconciliation");

                    b.ToTable("PaymentOrders", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("analysis_request_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<decimal?>("EducationScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("education_score");

                    b.Property<decimal>("ExperienceScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("experience_score");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<decimal>("FormatScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("format_score");

                    b.Property<bool>("IsSystemError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_error");

                    b.Property<string>("MandatoryWarningsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mandatory_warnings_json");

                    b.Property<int>("NormalizedDenominator")
                        .HasColumnType("int")
                        .HasColumnName("normalized_denominator");

                    b.Property<int>("OverallScore")
                        .HasColumnType("int")
                        .HasColumnName("overall_score");

                    b.Property<string>("ReportDetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("report_details_json");

                    b.Property<string>("ScoreLabel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("score_label");

                    b.Property<decimal>("SkillsScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("skills_score");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("AnalysisRequestId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Reports_analysis_request");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Reports_expires")
                        .HasFilter("[is_system_error] = 0");

                    b.ToTable("Reports", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.SupportAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("CVFileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cv_file_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("granted_by_user_id");

                    b.Property<Guid>("GrantedToUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("granted_to_user_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("CVFileId");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("GrantedToUserId");

                    b.HasIndex("TicketId", "GrantedToUserId", "ExpiresAt")
                        .HasDatabaseName("IX_SupportAccessGrants_lookup")
                        .HasFilter("[revoked_at] IS NULL");

                    b.ToTable("SupportAccessGrants", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("issue_description");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("report_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("resolved_at");

                    b.Property<DateTimeOffset>("SlaDueAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("sla_due_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ticket_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ReportId");

                    b.HasIndex("TicketCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_SupportTickets_code");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "SlaDueAt")
                        .HasDatabaseName("IX_SupportTickets_status_sla");

                    b.ToTable("SupportTickets", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_role");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.UserBalance", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("FreeTrialCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("free_trial_credits");

                    b.Property<int>("HeldCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("held_credits");

                    b.Property<int>("PaidCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("paid_credits");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("UserId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("UserId"));

                    b.ToTable("UserBalances", "dbo");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.AnalysisRequest", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.CVFile", "CVFile")
                        .WithMany("AnalysisRequests")
                        .HasForeignKey("CVFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AnalysisRequests_CVFiles");

                    b.HasOne("CVAnalysis.Domain.Entities.JobDescription", "JobDescription")
                        .WithMany("AnalysisRequests")
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AnalysisRequests_JobDescriptions");

                    b.HasOne("CVAnalysis.Domain.Entities.User", "User")
                        .WithMany("AnalysisRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AnalysisRequests_Users");

                    b.Navigation("CVFile");

                    b.Navigation("JobDescription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.CVFile", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.User", "User")
                        .WithMany("CVFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CVFiles_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.CompensationRequest", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_CompensationRequests_ApprovedByUser");

                    b.HasOne("CVAnalysis.Domain.Entities.User", "ProposedByUser")
                        .WithMany()
                        .HasForeignKey("ProposedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CompensationRequests_ProposedByUser");

                    b.HasOne("CVAnalysis.Domain.Entities.SupportTicket", "SupportTicket")
                        .WithOne("CompensationRequest")
                        .HasForeignKey("CVAnalysis.Domain.Entities.CompensationRequest", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CompensationRequests_Tickets");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("ProposedByUser");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.CreditLedger", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.User", "User")
                        .WithMany("CreditLedgers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CreditLedger_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.CreditPackage", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CreditPackages_Users");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.JobDescription", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.User", "User")
                        .WithMany("JobDescriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_JobDescriptions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.OptimizedBulletPoint", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.Report", "Report")
                        .WithMany("OptimizedBulletPoints")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OptimizedBulletPoints_Reports");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.PaymentOrder", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.CreditPackage", "CreditPackage")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentOrders_CreditPackages");

                    b.HasOne("CVAnalysis.Domain.Entities.User", "ReconciledByUser")
                        .WithMany()
                        .HasForeignKey("ReconciledByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_PaymentOrders_ReconciledByUser");

                    b.HasOne("CVAnalysis.Domain.Entities.User", "User")
                        .WithMany("PaymentOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentOrders_Users");

                    b.Navigation("CreditPackage");

                    b.Navigation("ReconciledByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.Report", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.AnalysisRequest", "AnalysisRequest")
                        .WithOne("Report")
                        .HasForeignKey("CVAnalysis.Domain.Entities.Report", "AnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reports_AnalysisRequests");

                    b.Navigation("AnalysisRequest");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.SupportAccessGrant", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.CVFile", "CVFile")
                        .WithMany("SupportAccessGrants")
                        .HasForeignKey("CVFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SupportAccessGrants_CVFiles");

                    b.HasOne("CVAnalysis.Domain.Entities.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SupportAccessGrants_GrantedByUser");

                    b.HasOne("CVAnalysis.Domain.Entities.User", "GrantedToUser")
                        .WithMany()
                        .HasForeignKey("GrantedToUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SupportAccessGrants_GrantedToUser");

                    b.HasOne("CVAnalysis.Domain.Entities.SupportTicket", "SupportTicket")
                        .WithMany("SupportAccessGrants")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SupportAccessGrants_Tickets");

                    b.Navigation("CVFile");

                    b.Navigation("GrantedByUser");

                    b.Navigation("GrantedToUser");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.SupportTicket", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_SupportTickets_AssignedToUser");

                    b.HasOne("CVAnalysis.Domain.Entities.Report", "Report")
                        .WithMany("SupportTickets")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SupportTickets_Reports");

                    b.HasOne("CVAnalysis.Domain.Entities.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SupportTickets_Users");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.UserBalance", b =>
                {
                    b.HasOne("CVAnalysis.Domain.Entities.User", "User")
                        .WithOne("UserBalance")
                        .HasForeignKey("CVAnalysis.Domain.Entities.UserBalance", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserBalances_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.AnalysisRequest", b =>
                {
                    b.Navigation("Report");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.CVFile", b =>
                {
                    b.Navigation("AnalysisRequests");

                    b.Navigation("SupportAccessGrants");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.CreditPackage", b =>
                {
                    b.Navigation("PaymentOrders");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.JobDescription", b =>
                {
                    b.Navigation("AnalysisRequests");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.Report", b =>
                {
                    b.Navigation("OptimizedBulletPoints");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.SupportTicket", b =>
                {
                    b.Navigation("CompensationRequest");

                    b.Navigation("SupportAccessGrants");
                });

            modelBuilder.Entity("CVAnalysis.Domain.Entities.User", b =>
                {
                    b.Navigation("AnalysisRequests");

                    b.Navigation("CVFiles");

                    b.Navigation("CreditLedgers");

                    b.Navigation("JobDescriptions");

                    b.Navigation("PaymentOrders");

                    b.Navigation("SupportTickets");

                    b.Navigation("UserBalance");
                });
#pragma warning restore 612, 618
        }
    }
}
